export const UserErrorType = {
	ERROR_EMAIL: "ERROR_EMAIL",
	ERROR_FIRST_NAME: "ERROR_FIRST_NAME",
	ERROR_LAST_NAME: "ERROR_LAST_NAME",
	ERROR_PASSWORD: "ERROR_PASSWORD",
	ERROR_EMAIL_OR_PASSWORD: "ERROR_EMAIL_OR_PASSWORD",
};

export const RecipeErrorType = {
	ERROR_TITLE: "ERROR_TITLE",
	ERROR_DESCRIPTION: "ERROR_DESCRIPTION",
	ERROR_URL_IMAGE: "ERROR_URL_IMAGE",
	ERROR_INGREDIENTS: "ERROR_INGREDIENTS",
	ERROR_INSTRUCTIONS: "ERROR_INSTRUCTIONS",
	ERROR_CATEGORIES: "ERROR_CATEGORIES",
};
